name: Output and Artifact workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event) }}"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-dep-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run lint
      - run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      file-output-value: ${{ steps.output_id.outputs.file-value }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: "~/.npm"
          key: node-dep-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run build
      - id: output_id
        run: find dist/assets/*.js -type f -execdir echo 'file-value={}' >> $GITHUB_OUTPUT ';'
      - uses: actions/upload-artifact@v4
        with:
          path: dist
          name: build-artifact
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-dep-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: echo ${{ needs.build.outputs.file-output-value }}
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - run: echo "Deploying ..."